[[alsa_plugins]]
arch = "aarch64"
git-tree-sha1 = "499d4a686df8d11db591ac295217b8711ed6accb"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "75fdc0b8602b327c991bb7d0224499dc698bc8ef7e4e5bf7e2b336afdd311716"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.12+0/alsa_plugins.v1.2.12.aarch64-linux-gnu.tar.gz"
[[alsa_plugins]]
arch = "aarch64"
git-tree-sha1 = "ec6734c28cd9bd3bd0473af31663abadf5b3df53"
libc = "musl"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "20c6c0e3524695fc9c56565eb6e238531964dab6e530b3c54409277738afddb0"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.12+0/alsa_plugins.v1.2.12.aarch64-linux-musl.tar.gz"
[[alsa_plugins]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c43f4348cfe87abc3310baa70214d39c6e4d03ca"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "c0ec597e7fd455e4c86d91cfdf2503306058b102992008126795e14df4a6e070"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.12+0/alsa_plugins.v1.2.12.armv7l-linux-gnueabihf.tar.gz"
[[alsa_plugins]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "af9daa472967f783e2b2a055b610823d287ba1c3"
libc = "musl"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "b9057810b901e748bd0cd537b7a06074466720f3aa44996698635ff2fb265bc8"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.12+0/alsa_plugins.v1.2.12.armv7l-linux-musleabihf.tar.gz"
[[alsa_plugins]]
arch = "i686"
git-tree-sha1 = "06c5197c1b6370f6343af8fc6f42ca85e32a3f82"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "8b201a4868c4a81d41f8c9e4eaaf463260f486a1029a7ff466753f123c59f425"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.12+0/alsa_plugins.v1.2.12.i686-linux-gnu.tar.gz"
[[alsa_plugins]]
arch = "i686"
git-tree-sha1 = "b979c0f248c31979cb382e8dc4535cb0e98e7d20"
libc = "musl"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "168303331b8ebaa54a800199d4e822951a9490c8d5ae7adae8f9d5c91758101e"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.12+0/alsa_plugins.v1.2.12.i686-linux-musl.tar.gz"
[[alsa_plugins]]
arch = "powerpc64le"
git-tree-sha1 = "8ad5d1de96dbee90483a7f4264de3ee3fa81297c"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "7a0cec1b127b3919349f4a63a64199d478804f461babf12acf87f35deedd695c"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.12+0/alsa_plugins.v1.2.12.powerpc64le-linux-gnu.tar.gz"
[[alsa_plugins]]
arch = "x86_64"
git-tree-sha1 = "6fa8cea8163343f906025929c03955529cdf5fd4"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "1f70f29521e9aa44a1664f8e11a45caf38e0e6b7605c1dd521682a45427475f7"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.12+0/alsa_plugins.v1.2.12.x86_64-linux-gnu.tar.gz"
[[alsa_plugins]]
arch = "x86_64"
git-tree-sha1 = "a17a5b7b77b0ea84c5907cc0bac6bd529b495324"
libc = "musl"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "191dbaa3bf8fbf159ac23cefe5e10e201a8ad9f8ee5058d41820beb131f14cb8"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.12+0/alsa_plugins.v1.2.12.x86_64-linux-musl.tar.gz"
