[[alsa_plugins]]
arch = "aarch64"
git-tree-sha1 = "b89ff7f8dc8d9902a7be9efe0f04626f2016b6d3"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "18ed64a4c60767d3e53edbbea2c3bef1f9558959335f4e2f0bbdf4a0135c2605"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.14+0/alsa_plugins.v1.2.14.aarch64-linux-gnu.tar.gz"
[[alsa_plugins]]
arch = "aarch64"
git-tree-sha1 = "c85435e57c2308af6080afe55b831a5e48b40ebd"
libc = "musl"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "15c808c44f0a95f48d5027faf6697fe29baee50100116930cabf3f8dcb0a096f"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.14+0/alsa_plugins.v1.2.14.aarch64-linux-musl.tar.gz"
[[alsa_plugins]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b19e1f92afca3d01b791d0a30d44b73be4c46e7e"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "17a12f6b249525b55037a7847480a288884636cbbf172bfdb55ecec2e0b413d2"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.14+0/alsa_plugins.v1.2.14.armv7l-linux-gnueabihf.tar.gz"
[[alsa_plugins]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7e66189a54f11dcbd96700da63e1c0811abb1b5d"
libc = "musl"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "ed59f2526929248dec586094b3cb54bedf8cd22575fb0e60054d093424a9dc0c"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.14+0/alsa_plugins.v1.2.14.armv7l-linux-musleabihf.tar.gz"
[[alsa_plugins]]
arch = "i686"
git-tree-sha1 = "1503f17df1bdd4278bb186b114552502def21ac9"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "12c20960fa2946734d5ee0cab5db1c184b7b5dd9523e0ea87ddada16cd787f4c"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.14+0/alsa_plugins.v1.2.14.i686-linux-gnu.tar.gz"
[[alsa_plugins]]
arch = "i686"
git-tree-sha1 = "28ffe52fd821c57fe9ff2ac9db2a9a9edc955f99"
libc = "musl"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "ce1dcbc496e8dc458a798071d940f9827af0086950d37ddc8ee4586cdb425ca5"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.14+0/alsa_plugins.v1.2.14.i686-linux-musl.tar.gz"
[[alsa_plugins]]
arch = "powerpc64le"
git-tree-sha1 = "a8dee15ed2eeaa7008258aac7fa9020b9297f015"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "6eb1bfb8dcd86276d4bc3e690cb1e8a657edff37811cb10f725f6cba8bc7f3af"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.14+0/alsa_plugins.v1.2.14.powerpc64le-linux-gnu.tar.gz"
[[alsa_plugins]]
arch = "x86_64"
git-tree-sha1 = "1bdcb606a45637d941b49190510f3ad1901af144"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "aaa86ba925b1c81e3b9cb721f009f8a501ac0225bb5c25af5ae2ba7ff9a28692"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.14+0/alsa_plugins.v1.2.14.x86_64-linux-gnu.tar.gz"
[[alsa_plugins]]
arch = "x86_64"
git-tree-sha1 = "08685380b5b354158e94567a90da446d8448e44b"
libc = "musl"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "9919dddf3c7bf84625de4b742e74b785aafe4f3bb7e656e81f375f4783a60c3a"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.14+0/alsa_plugins.v1.2.14.x86_64-linux-musl.tar.gz"
