[[alsa_plugins]]
arch = "aarch64"
git-tree-sha1 = "4c49604571b4357ba1f55ae8a2c2a10714764ac2"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "6758c9a89324d39b8efc0a8b45afc8a9dbce57c1a8d9d739f97297840f0fb6b9"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.aarch64-linux-gnu.tar.gz"
[[alsa_plugins]]
arch = "aarch64"
git-tree-sha1 = "7ae2ff911a5978ad6abf3c4fa4200de3507affae"
libc = "musl"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "e3205aaac4efde9ec38b8d8196737025af83b8a0f0b0529a16cbf72c7ec50d65"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.aarch64-linux-musl.tar.gz"
[[alsa_plugins]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4d41ef953d963bda5656780c6b07f13d8dd6b933"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "1eab82e0a7bccbd666d2f73ad364fb89d986a3fbccd72845ff9d37601ee3b166"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.armv7l-linux-gnueabihf.tar.gz"
[[alsa_plugins]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "70cccee74d2f767eb7c0f3acdceee1c7c55a720b"
libc = "musl"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "0c045d52d2f0f65ccb3a77782a170e6fecccf8f73a3f582e292cddefcba45ad7"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.armv7l-linux-musleabihf.tar.gz"
[[alsa_plugins]]
arch = "i686"
git-tree-sha1 = "12d9241fff8b0355c850e36f5666c56ae8b88819"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "e093ae8ec1d6a0bbe2403044b6ab3df85d0a3adbf91c2f7cd43f324fa4e4f822"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.i686-linux-gnu.tar.gz"
[[alsa_plugins]]
arch = "i686"
git-tree-sha1 = "f160905bffa5a095251ef52700f20376e2eb0a6f"
libc = "musl"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "b8a146cb8bc6f9db89ee8c3abffa6baa8711bc541c27f7b787d529fc6d088e45"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.i686-linux-musl.tar.gz"
[[alsa_plugins]]
arch = "powerpc64le"
git-tree-sha1 = "dcc1f726563ba93bfc39de4996bab78cf4e41b7d"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "62825e038d3f6a23b5ea4ff1262d463f601e031be09a5be447ee60552dc39315"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.powerpc64le-linux-gnu.tar.gz"
[[alsa_plugins]]
arch = "x86_64"
git-tree-sha1 = "937f1f11a618d5f717fa5208e57f26b021971d13"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "1d7aebed1b44cbe5976f255879c8c184ca2e86feaa3c538794ca25b0dab8c547"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.x86_64-linux-gnu.tar.gz"
[[alsa_plugins]]
arch = "x86_64"
git-tree-sha1 = "831557ebe5a632e728bbd3762ec49fde34fb792e"
libc = "musl"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "fa4d9bd6c3bf67e316d71368b627654a12210a717d5bf10808b62551e8ef4cca"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.x86_64-linux-musl.tar.gz"
