[[alsa_plugins]]
arch = "aarch64"
git-tree-sha1 = "abe36b71c65ef27a4660bf2196523940b038fe42"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "a2712ddc8b2ea811de525154e9ba5d9e1731b3184c7e9aab32ba798328de757c"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.aarch64-linux-gnu.tar.gz"
[[alsa_plugins]]
arch = "aarch64"
git-tree-sha1 = "3b56bfeec8bddee2eb74ff5c29b59e4121d59657"
libc = "musl"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "bb3efc669500640de741cd8e2df11076a093188e989e6a348c0a100f97bc8ce8"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.aarch64-linux-musl.tar.gz"
[[alsa_plugins]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4e99f63b7c9649cd26fa97f6278e9633503fe0d3"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "5f96ddcc040f76b64cd87350bebebfc75dccd61eae71f84a790bc7293ca46b53"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.armv7l-linux-gnueabihf.tar.gz"
[[alsa_plugins]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7c64d1dc338f5ab3b2a0c326fb0e720be0c409a5"
libc = "musl"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "ac18421b137c0b5aba4471f7a2f1f9611d5f4e51927b403efdff743ac91fda3f"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.armv7l-linux-musleabihf.tar.gz"
[[alsa_plugins]]
arch = "i686"
git-tree-sha1 = "d28c54506142ef86c62a0b7c56e6f05cf38c9997"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "c2528d66978528afa1c2cbb327f017f8d371b0f998a473ad740e858f5784af3b"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.i686-linux-gnu.tar.gz"
[[alsa_plugins]]
arch = "i686"
git-tree-sha1 = "80d0ed8660609a4db0313224235be35c90514bbe"
libc = "musl"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "d1fd5738f1eabb796458bcd0060b71666b68c55ec4e41b6db3e447279ce08119"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.i686-linux-musl.tar.gz"
[[alsa_plugins]]
arch = "powerpc64le"
git-tree-sha1 = "10ebc065462d8439b6623f698561dc097fa7d9c2"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "0b1dc5d37b9a9b7a4572ea1fa89977cb2a84a0bd36ec9677f571423b1826853a"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.powerpc64le-linux-gnu.tar.gz"
[[alsa_plugins]]
arch = "x86_64"
git-tree-sha1 = "0cd12c59eaf8e759e71e91a333dd2457b38bc590"
libc = "glibc"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "723f70a5a2f501a65840cf2ba8712ab3d32343a3dd599a416c4f08745f8d6b19"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.x86_64-linux-gnu.tar.gz"
[[alsa_plugins]]
arch = "x86_64"
git-tree-sha1 = "8a2ae94841f938a6066e682d100f4ab6b5f9e1c1"
libc = "musl"
os = "linux"

    [[alsa_plugins.download]]
    sha256 = "2456bc4dc613788c183424d06fd29a3376c1f89097a4281f06e4d4073d710a2b"
    url = "https://github.com/JuliaBinaryWrappers/alsa_plugins_jll.jl/releases/download/alsa_plugins-v1.2.13+0/alsa_plugins.v1.2.13.x86_64-linux-musl.tar.gz"
